import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SearchBar from "@/components/SearchBar";

export const metadata: Metadata = {
  title: "Entertainment Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-body flex bg-primary-dark-blue text-white overflow-hidden">
        <div className="w-[15vh] h-screen">
          <Navbar />
        </div>
        <div className="w-full h-screen overflow-y-auto scrollbar-hide">
          <SearchBar />
          <div className=" overflow-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
